### ISSUE TITLE
Cargo `winrt` crate name already taken

### ISSUE THREAD

**Issue by Boddlnagg** [contextfree/winrt-rust#6]
See https://crates.io/crates/winrt. Since that is the crate name that I would have chosen, and the code in that crate is not more than an experiment, and there is no linked repository where further development might happen, maybe it's possible to contact the author to ask whether the crate ownership can be moved? This is possible using `cargo owner --add <GitHub Username>`.

@Miot: are you still interested in maintaining your crate or would you agree to give ownership to me and/or @contextfree?

**Comment by Miot** [comment]
Hi Patrick Reisert:

I have received your mail and I agree with to give ownership to you.Enjoy yourself.

From Miot,China.

From: Patrick Reisert
Date: 2016-06-09 07:26
To: contextfree/winrt-rust
CC: Miot; Mention
Subject: [contextfree/winrt-rust] Cargo `winrt` crate already exists (#6)
See https://crates.io/crates/winrt. Since that is the crate name that I would have chosen, and the code in that crate is not more than an experiment, and there is no linked repository where further development might happen, maybe it's possible to contact the author to ask whether the crate ownership can be moved? This is possible using cargo owner --add <GitHub Username>.
@Miot: are you still interested in maintaining your crate or would you agree to give ownership to me and/or @contextfree?

**Comment by Boddlnagg** [comment]
Great, thank you! :smiley:  Can you please execute the following in your `winrt` directory (or in a new empty project with the same name, which you can create using `cargo new winrt`)?

```
cargo owner --add Boddlnagg
cargo owner --add contextfree
```

**Comment by Miot** [comment]
I am sorry about that I unable to use the Github skillfully, also I afraid that I can't surely understand what you said.     OTZ

Please tell me how I can do to exchange the owner  of the "cargo"???
From: Patrick Reisert
Date: 2016-06-09 15:44
To: contextfree/winrt-rust
CC: Miot; Mention
Subject: Re: [contextfree/winrt-rust] Cargo `winrt` crate name already taken (#6)
Great, thank you! ???? Can you please execute the following in your winrt directory (or in a new empty project with the same name, which you can create using cargo new winrt)?
cargo owner --add Boddlnagg
cargo owner --add contextfree

**Comment by Boddlnagg** [comment]
You have used cargo to publish your crate to crates.io. You have to use the cargo program to give ownership to anyone else. You also have to login with your API token. All this is described on http://doc.crates.io/crates-io.html

After you have logged in, you go into your winrt project directory (that is the directory that you used to publish your crate). If you don't have that anymore, you can create a new empty project with the same name: cargo new winrt

Then in that project directory, you execute the following commands:
cargo owner --add Boddlnagg
cargo owner --add contextfree

**Comment by Boddlnagg** [comment]
@Miot: Have you tried to do this already? If something is not clear yet, I can try to explain it again.
