### ISSUE TITLE
Some special cases are needed for the snake case conversion

### ISSUE THREAD

**Issue by chris-morgan** [contextfree/winrt-rust#65]
Specifically I have in mind “JavaScript” as in the `IsJavaScriptEnabled` property of `Windows.Web.UI.WebViewControlSettings`, which currently becomes `is_java_script_enabled` but should rather be `is_javascript_enabled`, that being idiomatic.

I’m then vaguely guessing that there will be other special cases too. If there is already something in place for special-casing things, then this property should be added to it, and if not then such a capability should be added.

**Comment by chris-morgan** [comment]
I might as well mention this case here too: a sibling property `IsIndexedDBEnabled` is rendered incorrectly as `is_indexed_dbenabled` rather than `is_indexed_db_enabled` (the straightforward translation) or `is_indexeddb_enabled` (which I’d mildly prefer, as a special case).

**Comment by Boddlnagg** [comment]
Thanks! There is currently no way to special case the conversion, and your second comment pointed out a flaw in the conversion that doesn't even relate to special cases. Having fixed that second issue, I have identified a few more names that are worth adding to a list of special cases:
- DBm -> dbm
- UInt -> uint
- DUInt -> duint
- 3D -> 3d (currently completely broken because it inserts a `_` between `3` and `d`
- 3MF -> 3mf
- OAuth -> oauth
- DolbyDDPlus -> dolby_ddplus
- MPeg -> mpeg
- WMAudio -> wmaudio
- URLs -> urls
- ESim -> esim
- EFSpn -> efspn
- EFOns -> efons
- EFOpl -> efopl
- EFPnn -> efpnn
- ETag -> etag
- IndexedDB -> indexeddb
- JavaScript -> javascript

And also sometimes there are interface names contained in method names:
- CreateFromIMediaSource -> `create_from_imedia_source`/`create_from_imediasource`?
- CreateMemoryBufferOverIBuffer -> `create_memory_buffer_over_ibuffer`
- StartAnimationWithIAnimationObject -> `start_animation_with_ianimation_object`/`start_animation_with_ianimationobject` ?

**Comment by Boddlnagg** [comment]
I've now implemented a much better heuristic for detecting and splitting words/numbers, and also added a list of exceptions which will be left intact as single words.
